### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by bart** [irislib/iris-lib#49]
Compared to https://github.com/irislib/iris-messenger/tree/master/src/js/iris-lib (last update yesterday) it looks like the "original" library isn't updated for 4 months now. @mmalmi Will you create new versions in the future or should we copy files from the `iris-messenger`? Thanks!

**Comment by mmalmi** [comment]
For now it's best to copy from `iris-messenger`.

I'm merging iris-lib and iris-messenger into the same repo, because I want to export iris-messenger components and utilities as parts of the lib.
